import fs from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';

function migration(): string {
  const file = path.join(process.cwd(), 'supabase/migrations/20260916074000_grid_chat_sync_notifications.sql');
  if (!fs.existsSync(file)) throw new Error('Grid chat sync migration not found');
  return fs.readFileSync(file, 'utf8').toLowerCase();
}

describe('Grid chat incremental sync + notifications SQL', () => {
  it('adds a monotonic message sequence cursor for reliable incremental sync', () => {
    const sql = migration();
    expect(sql).toContain('sequence_no bigint');
    expect(sql).toContain('generated by default as identity');
    expect(sql).toContain('grid_chat_messages_channel_sequence_idx');
  });

  it('counts system messages as unread and excludes the reader + blocked players', () => {
    const sql = migration();
    expect(sql).toContain('grid_chat_unread_count');
    expect(sql).toContain("m.sender_kind = 'system'");
    expect(sql).toContain('m.sender_player_id <> p_player_id');
    expect(sql).toContain('public.grid_chat_blocks');
  });

  it('updates notification preference only for an active channel member', () => {
    const sql = migration();
    expect(sql).toContain('grid_set_chat_notifications');
    expect(sql).toContain('notifications_enabled = p_enabled');
    expect(sql).toContain('left_at is null');
    expect(sql).toContain('chat_membership_required');
  });

  it('keeps sync helper functions server-only', () => {
    const sql = migration();
    expect(sql.match(/revoke all on function public\.grid_/g)?.length).toBeGreaterThanOrEqual(2);
    expect(sql.match(/to service_role/g)?.length).toBeGreaterThanOrEqual(2);
  });
});
