/**
 * Canton Quests — Contextual Transmission Engine
 * =================================================
 * The central resolver every live-game system calls to decide "should the
 * Commander say something right now, and if so, what?" — replacing a
 * pattern of scattered per-page conditionals (the Commander Videos mission
 * hand-wired 13 of these one at a time) with one reusable rule table and
 * one resolve/show pair of functions.
 *
 * Reuses, never duplicates:
 *   - the real 1-15 Commander video archive (lib/commander-transmissions.ts)
 *     — a rule may reference one of these numbered videos, but ONLY when
 *     that video's actual content genuinely matches the trigger. Most of
 *     the newer trigger names below have no matching video and resolve to
 *     short text (QuestCommanderTransmission type: 'PHOTO_MESSAGE') instead
 *     — never a guessed video assignment.
 *   - the per-quest QuestCommanderTransmission fields already on Quest
 *     (commanderTransmission / completionTransmission / etc, lib/types.ts)
 *     for quest_intro/quest_completion — this engine deliberately does NOT
 *     register a generic default for those two triggers; callers pass the
 *     quest's own authored transmission in as `inlineContent`.
 *   - lib/transmission-viewed-state.ts for de-dupe AND (new) cooldown.
 *   - GameMomentManager (showGameMoment) — the resolved output flows into
 *     the exact same 'commander-transmission' moment that already exists.
 *
 * Server state must cause transmissions; transmissions never create it.
 * Nothing in this file performs a database read or write, awards XP/entries,
 * or mutates any game state — it only ever returns a display payload
 * (QuestCommanderTransmission | undefined) or a boolean "should I show one."
 */

import { CommanderTransmissionTrigger, showGameMoment } from './game-effects';
import { QuestCommanderTransmission, StartingPath } from './types';
import { getTransmissionById, toGameplayTransmission } from './commander-transmissions';
import { isKnownCantonLaunchSlug } from './launch-status';
import { hasViewedTransmission, hasActiveCooldown, markTransmissionViewed } from './transmission-viewed-state';

export interface ContextualTransmissionContext {
  trigger: CommanderTransmissionTrigger;
  eventSlug: string;
  playerId?: string;
  path?: StartingPath;
  questId?: string;
  /** Stable de-dupe/cooldown identity. Defaults to questId, else the trigger name itself. */
  subjectKey?: string;
  /**
   * Ad-hoc content authored outside the static rule table — a GM-authored
   * live-event message, or a quest's own per-quest QuestCommanderTransmission
   * being routed through this engine's de-dupe/cooldown/GameMoment plumbing.
   * When present, this always wins over any registered rule.
   */
  inlineContent?: { headline: string; message: string; cta?: string; posterKey?: string; replayable?: boolean };
  /** Presentational only — see QuestCommanderTransmission.countdownEndsAt. */
  countdownEndsAt?: string;
  /** Server-computed clock. Real callers always pass new Date() (or omit it) — never a client-supplied value. */
  now?: Date;
  /** Test-only: substitute the rule table so window/cooldown/priority behavior can be verified without touching the real registry. Never set by production callers. */
  rulesOverride?: ContextualTransmissionRule[];
}

export interface ContextualTransmissionRule {
  id: string;
  trigger: CommanderTransmissionTrigger;
  /** Only matches this exact starting path when set; undefined = any path / city-wide. */
  pathScope?: StartingPath;
  /** Highest-priority matching rule wins when more than one candidate qualifies. */
  priority: number;
  /** Auto-show at most once ever, per player, per subjectKey. */
  onceParPlayer: boolean;
  /** Whether a manual "replay" control may re-open this after first view. */
  replayable: boolean;
  /** For a repeatable (onceParPlayer: false) trigger, the minimum gap between two auto-shows. */
  cooldownMs?: number;
  startsAt?: string;
  endsAt?: string;
  content: { kind: 'video'; commanderVideoId: number } | { kind: 'text'; headline: string; message: string; cta?: string };
}

/**
 * The default rule table. A trigger whose real content is inherently
 * per-quest or per-mission-stage (quest_intro, quest_completion,
 * final_hours, finale) has NO entry here — callers pass `inlineContent`
 * (the quest's own authored QuestCommanderTransmission, or content
 * generated by the calling system) rather than getting a fabricated
 * generic message. Every other trigger gets a short, generic, on-brand
 * text default (never a numbered video unless the content genuinely
 * matches) so a caller that hasn't authored anything specific still gets
 * something reasonable — mission_entry / path_selection / path_selected /
 * xp_awarded / drawing_entry_awarded / leaderboard_milestone are the only
 * ones that resolve to a real numbered video, reusing the exact same
 * content as the equivalent cipher_* trigger, since it's literally the same
 * moment.
 */
export const CONTEXTUAL_TRANSMISSION_RULES: ContextualTransmissionRule[] = [
  { id: 'mission-entry-cold-open', trigger: 'mission_entry', priority: 10, onceParPlayer: true, replayable: true, content: { kind: 'video', commanderVideoId: 1 } },
  { id: 'path-selection-three-doors', trigger: 'path_selection', priority: 10, onceParPlayer: true, replayable: true, content: { kind: 'video', commanderVideoId: 9 } },
  { id: 'path-selected-family', trigger: 'path_selected', pathScope: 'family', priority: 10, onceParPlayer: true, replayable: true, content: { kind: 'video', commanderVideoId: 6 } },
  { id: 'path-selected-challenge', trigger: 'path_selected', pathScope: 'challenge', priority: 10, onceParPlayer: true, replayable: true, content: { kind: 'video', commanderVideoId: 7 } },
  { id: 'path-selected-secret', trigger: 'path_selected', pathScope: 'secret', priority: 10, onceParPlayer: true, replayable: true, content: { kind: 'video', commanderVideoId: 8 } },
  { id: 'xp-awarded-first', trigger: 'xp_awarded', priority: 10, onceParPlayer: true, replayable: true, content: { kind: 'video', commanderVideoId: 12 } },
  { id: 'drawing-entry-awarded-first', trigger: 'drawing_entry_awarded', priority: 10, onceParPlayer: true, replayable: true, content: { kind: 'video', commanderVideoId: 13 } },
  { id: 'leaderboard-milestone-first', trigger: 'leaderboard_milestone', priority: 10, onceParPlayer: true, replayable: true, content: { kind: 'video', commanderVideoId: 14 } },

  {
    id: 'badge-awarded-default',
    trigger: 'badge_awarded',
    priority: 1,
    onceParPlayer: false,
    replayable: false,
    cooldownMs: 30_000,
    content: { kind: 'text', headline: 'BADGE SECURED', message: "The Commander's ledger updates in real time — well earned.", cta: 'CONTINUE' },
  },
  {
    id: 'flash-drop-default',
    trigger: 'flash_drop',
    priority: 1,
    onceParPlayer: false,
    replayable: false,
    cooldownMs: 60_000,
    content: { kind: 'text', headline: 'SIGNAL ACTIVE', message: 'A flash signal has gone live somewhere in the grid. Move fast — it will not last.', cta: 'VIEW SIGNAL' },
  },
  {
    id: 'city-event-default',
    trigger: 'city_event',
    priority: 1,
    onceParPlayer: false,
    replayable: false,
    cooldownMs: 60_000,
    content: { kind: 'text', headline: 'CITY EVENT', message: 'Something is shifting across all of Canton right now.', cta: 'CONTINUE' },
  },
  {
    id: 'sector-event-default',
    trigger: 'sector_event',
    priority: 1,
    onceParPlayer: false,
    replayable: false,
    cooldownMs: 60_000,
    content: { kind: 'text', headline: 'SECTOR SIGNAL', message: 'A district-scoped signal has gone active.', cta: 'CONTINUE' },
  },
  {
    id: 'community-milestone-default',
    trigger: 'community_milestone',
    priority: 1,
    onceParPlayer: false,
    replayable: false,
    cooldownMs: 30_000,
    content: { kind: 'text', headline: 'CITY MILESTONE', message: 'The whole city just crossed a threshold together.', cta: 'CONTINUE' },
  },
  {
    id: 'npc-event-default',
    trigger: 'npc_event',
    priority: 1,
    onceParPlayer: false,
    replayable: false,
    cooldownMs: 60_000,
    content: { kind: 'text', headline: 'FIELD CONTACT', message: 'Someone in the field is carrying a signal for the Commander.', cta: 'CONTINUE' },
  },
  {
    id: 'player-link-default',
    trigger: 'player_link',
    priority: 1,
    onceParPlayer: false,
    replayable: false,
    cooldownMs: 10_000,
    content: { kind: 'text', headline: 'LINK ESTABLISHED', message: 'Two signals just connected in the field.', cta: 'CONTINUE' },
  },
  {
    id: 'watcher-signal-default',
    trigger: 'watcher_signal',
    priority: 1,
    onceParPlayer: false,
    replayable: false,
    cooldownMs: 60_000,
    content: { kind: 'text', headline: '???', message: 'Something noticed you.', cta: 'CONTINUE' },
  },
  {
    id: 'emergency-default',
    trigger: 'emergency',
    priority: 1,
    onceParPlayer: false,
    replayable: false,
    content: { kind: 'text', headline: 'COMMANDER ALERT', message: 'An urgent message from Command.', cta: 'ACKNOWLEDGE' },
  },
  {
    id: 'district-sigil-unlocked-default',
    trigger: 'district_sigil_unlocked',
    priority: 1,
    onceParPlayer: false,
    replayable: false,
    cooldownMs: 5_000,
    content: { kind: 'text', headline: 'SIGIL RESOLVED', message: "A sigil resolves. One piece of Canton's cipher is now yours.", cta: 'CONTINUE' },
  },
  {
    id: 'fragment-recovered-default',
    trigger: 'fragment_recovered',
    priority: 1,
    onceParPlayer: false,
    replayable: false,
    cooldownMs: 5_000,
    content: { kind: 'text', headline: 'FRAGMENT RECOVERED', message: 'A trace has been added to the archive.', cta: 'CONTINUE' },
  },
];

function findMatchingRule(context: ContextualTransmissionContext): ContextualTransmissionRule | undefined {
  const now = context.now ?? new Date();
  const nowMs = now.getTime();
  const candidates = (context.rulesOverride ?? CONTEXTUAL_TRANSMISSION_RULES).filter((rule) => {
    if (rule.trigger !== context.trigger) return false;
    if (rule.pathScope && rule.pathScope !== context.path) return false;
    if (rule.startsAt && new Date(rule.startsAt).getTime() > nowMs) return false;
    if (rule.endsAt && new Date(rule.endsAt).getTime() <= nowMs) return false;
    return true;
  });
  if (candidates.length === 0) return undefined;
  return candidates.sort((a, b) => b.priority - a.priority)[0];
}

function subjectKeyFor(context: ContextualTransmissionContext): string {
  return context.subjectKey || context.questId || context.trigger;
}

/**
 * Pure resolution: given a context, what should the Commander show (if
 * anything)? Never touches storage, GameMomentManager, or any DB — see
 * showContextualTransmission for the version that actually fires it.
 * Always undefined for an event outside Founder's Cipher scope, or when
 * nothing matches.
 */
export function resolveContextualTransmission(context: ContextualTransmissionContext): QuestCommanderTransmission | undefined {
  if (!isKnownCantonLaunchSlug(context.eventSlug)) return undefined;

  if (context.inlineContent) {
    return {
      type: 'PHOTO_MESSAGE',
      headline: context.inlineContent.headline,
      message: context.inlineContent.message,
      posterKey: context.inlineContent.posterKey,
      cta: context.inlineContent.cta || 'CONTINUE',
      replayable: context.inlineContent.replayable ?? true,
      skippable: true,
      countdownEndsAt: context.countdownEndsAt,
    };
  }

  const rule = findMatchingRule(context);
  if (!rule) return undefined;

  if (rule.content.kind === 'video') {
    const entry = getTransmissionById(rule.content.commanderVideoId);
    if (!entry) return undefined;
    return toGameplayTransmission(entry);
  }

  return {
    type: 'PHOTO_MESSAGE',
    headline: rule.content.headline,
    message: rule.content.message,
    cta: rule.content.cta || 'CONTINUE',
    replayable: rule.replayable,
    skippable: true,
    countdownEndsAt: context.countdownEndsAt,
  };
}

/**
 * Whether this context should auto-fire right now — combines event scope,
 * once-per-player de-dupe, and cooldown. gm_announcement/emergency always
 * pass (they intentionally bypass de-dupe, matching the pre-existing rule
 * for gm_announcement — see lib/transmission-viewed-state.ts).
 */
export function shouldShowContextualTransmission(context: ContextualTransmissionContext): boolean {
  if (!isKnownCantonLaunchSlug(context.eventSlug)) return false;
  if (context.trigger === 'gm_announcement' || context.trigger === 'emergency') return true;

  const subjectKey = subjectKeyFor(context);

  if (context.inlineContent) {
    return !hasViewedTransmission(context.trigger, subjectKey, context.playerId);
  }

  const rule = findMatchingRule(context);
  if (!rule) return false;
  if (rule.onceParPlayer) return !hasViewedTransmission(context.trigger, subjectKey, context.playerId);
  if (rule.cooldownMs) return !hasActiveCooldown(context.trigger, subjectKey, rule.cooldownMs, context.playerId);
  return true;
}

/**
 * The one-call convenience every caller should reach for instead of
 * hand-rolling the shouldShow → resolve → mark → showGameMoment sequence:
 * resolves, checks eligibility, records the view, and queues the
 * GameMoment. Returns whether it actually fired. Client-side only (reads
 * localStorage via transmission-viewed-state.ts and calls
 * GameMomentManager) — server code should call resolveContextualTransmission
 * directly and ship the result to the client instead.
 */
export function showContextualTransmission(context: ContextualTransmissionContext): boolean {
  if (!shouldShowContextualTransmission(context)) return false;
  const transmission = resolveContextualTransmission(context);
  if (!transmission) return false;

  const subjectKey = subjectKeyFor(context);
  markTransmissionViewed(context.trigger, subjectKey, context.playerId);
  showGameMoment({ type: 'commander-transmission', trigger: context.trigger, transmission, viewedStateKey: subjectKey });
  return true;
}
