// Canton Quests — Phase 1 Test Seed Data (Canton, Ohio)

import { City, QuestEvent, LocationInfo, Quest, Player } from './types';

export const SEED_CITY: City = {
  id: 'city-canton-oh',
  name: 'Canton',
  slug: 'canton-oh',
  state: 'OH',
  isActive: true,
  createdAt: '2026-08-01T00:00:00Z',
};

export const SEED_LOCATIONS: LocationInfo[] = [
  {
    id: 'loc-centennial-plaza',
    cityId: SEED_CITY.id,
    name: 'Centennial Plaza',
    address: '330 Market Ave N, Canton, OH 44702',
    latitude: 40.7989,
    longitude: -81.3748,
    locationNotes: 'Downtown Canton central gathering space with outdoor screens and cafe seating.',
    isPartner: true,
  },
  {
    id: 'loc-mckinley-monument',
    cityId: SEED_CITY.id,
    name: 'McKinley National Memorial',
    address: '800 McKinley Monument Dr NW, Canton, OH 44708',
    latitude: 40.8064,
    longitude: -81.3933,
    locationNotes: 'Historic 108-step monument overlooking the park and city.',
    isPartner: false,
  },
  {
    id: 'loc-4th-st-mural',
    cityId: SEED_CITY.id,
    name: '4th Street Arts Corridor Mural',
    address: '4th St NW & Court Ave NW, Canton, OH 44702',
    latitude: 40.7995,
    longitude: -81.3755,
    locationNotes: 'Vibrant street art wall in the heart of downtown Canton Arts District.',
    isPartner: true,
  },
  {
    id: 'loc-aura-craft-coffee',
    cityId: SEED_CITY.id,
    name: 'Aura Craft Coffee',
    address: '414 4th St NW, Canton, OH 44702',
    latitude: 40.7998,
    longitude: -81.3761,
    locationNotes: 'Local partner coffee shop. Look near the espresso counter or patio area.',
    isPartner: true,
  },
  {
    id: 'loc-arcade-bar',
    cityId: SEED_CITY.id,
    name: 'Downtown Canton Arcade Vault',
    address: '218 Market Ave N, Canton, OH 44702',
    latitude: 40.7978,
    longitude: -81.3748,
    locationNotes: 'Retro arcade venue featuring vintage pinball and arcade cabinets.',
    isPartner: true,
  },
  {
    id: 'loc-music-hall',
    cityId: SEED_CITY.id,
    name: 'Canton Palace Theatre',
    address: '605 Market Ave N, Canton, OH 44702',
    latitude: 40.8012,
    longitude: -81.3748,
    locationNotes: 'Historic 1927 theater marquee and architectural gem of Canton.',
    isPartner: true,
  },
  {
    id: 'loc-hof-trail',
    cityId: SEED_CITY.id,
    name: 'Hall of Fame City Marker',
    address: '2121 George Halas Dr NW, Canton, OH 44708',
    latitude: 40.8211,
    longitude: -81.3985,
    locationNotes: 'Commemorative plaza marker celebrating Canton football heritage.',
    isPartner: false,
  },
  {
    id: 'loc-onesto-building',
    cityId: SEED_CITY.id,
    name: 'The Onesto Historic Entrance',
    address: '225 2nd St NW, Canton, OH 44702',
    latitude: 40.7971,
    longitude: -81.3752,
    locationNotes: 'Grand historic hotel building with ornate brass entrance doors.',
    isPartner: false,
  },
];

export const SEED_EVENT: QuestEvent = {
  id: 'evt-canton-vol-1',
  cityId: SEED_CITY.id,
  title: 'Canton Quest Weekend #1 — The Founder’s Cipher',
  slug: 'canton-weekend-1',
  description:
    'Explore Canton, Ohio like never before! Decode urban ciphers, scan hidden QR codes, capture iconic photos, and solve real-world mysteries across downtown Canton.',
  status: 'active',
  startTime: '2026-08-07T18:00:00Z',
  endTime: '2026-08-09T22:00:00Z',
  basicInstructions:
    '1. Select any available quest below.\n2. Travel to the location in Canton.\n3. Follow quest instructions and submit your proof.\n4. Earn XP, climb the leaderboard, and unlock secret missions!',
  createdAt: '2026-08-01T00:00:00Z',
};

export const SEED_QUESTS: Quest[] = [
  {
    id: 'qst-centennial-discovery',
    eventId: SEED_EVENT.id,
    locationId: 'loc-centennial-plaza',
    location: SEED_LOCATIONS[0],
    title: 'Centennial Beacon Check-In',
    slug: 'centennial-beacon',
    description: 'Reach Centennial Plaza in downtown Canton and initialize your field scanner.',
    instructions: 'Stand anywhere near the central lawn at Centennial Plaza and tap the check-in scanner.',
    pointValue: 50,
    difficulty: 'easy',
    category: 'exploration',
    verificationType: 'checkin',
    proofRequirement: 'Confirm physical check-in at Centennial Plaza.',
    isFlash: false,
    status: 'active',
    sortOrder: 1,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'qst-mckinley-cipher',
    eventId: SEED_EVENT.id,
    locationId: 'loc-mckinley-monument',
    location: SEED_LOCATIONS[1],
    title: 'The McKinley Monument Year',
    slug: 'mckinley-monument-year',
    description: 'Find the dedication year engraved on the bronze cornerstone of the McKinley Memorial.',
    instructions: 'Locate the historic bronze plaque near the monument stairs entrance and enter the 4-digit dedication year.',
    pointValue: 150,
    difficulty: 'medium',
    category: 'puzzle',
    verificationType: 'passphrase',
    targetCode: '1897',
    proofRequirement: 'Enter the 4-digit year found on the cornerstone plaque.',
    isFlash: false,
    status: 'active',
    sortOrder: 2,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'qst-4th-st-mural-photo',
    eventId: SEED_EVENT.id,
    locationId: 'loc-4th-st-mural',
    location: SEED_LOCATIONS[2],
    title: 'Mural Pose Challenge',
    slug: '4th-st-mural-pose',
    description: 'Recreate a high-energy victory pose with the giant Arts District street mural.',
    instructions: 'Take a photo of yourself or your team posing in front of the 4th Street mural. Upload the picture for review.',
    pointValue: 200,
    difficulty: 'medium',
    category: 'creative',
    verificationType: 'photo',
    proofRequirement: 'Upload a photo showing team members in front of the mural.',
    isFlash: false,
    status: 'active',
    sortOrder: 3,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'qst-aura-coffee-qr',
    eventId: SEED_EVENT.id,
    locationId: 'loc-aura-craft-coffee',
    location: SEED_LOCATIONS[3],
    title: 'Aura Brew Frequency',
    slug: 'aura-coffee-scan',
    description: 'Scan the official Canton Quests QR code displayed inside Aura Craft Coffee.',
    instructions: 'Find the Canton Quests QR card near the counter at Aura Craft Coffee and scan it with your camera or enter the code.',
    pointValue: 100,
    difficulty: 'easy',
    category: 'business_partner',
    verificationType: 'qr',
    targetCode: 'AURA-BREW-2026',
    proofRequirement: 'Scan or type the QR code passphrase displayed at Aura Craft Coffee.',
    isFlash: false,
    status: 'active',
    sortOrder: 4,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'qst-arcade-high-score-video',
    eventId: SEED_EVENT.id,
    locationId: 'loc-arcade-bar',
    location: SEED_LOCATIONS[4],
    title: 'Arcade Champion High-Five',
    slug: 'arcade-champion-video',
    description: 'Record a short 5-second celebratory video at the Arcade Vault.',
    instructions: 'Capture a quick clip of your team cheering or high-fiving in front of a pinball machine or classic arcade machine.',
    pointValue: 350,
    difficulty: 'hard',
    category: 'photo_video',
    verificationType: 'video',
    proofRequirement: 'Upload a short video clip (or video link) showing your arcade celebration.',
    isFlash: false,
    status: 'active',
    sortOrder: 5,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'qst-palace-theatre-year',
    eventId: SEED_EVENT.id,
    locationId: 'loc-music-hall',
    location: SEED_LOCATIONS[5],
    title: 'Canton Palace Marquee Lore',
    slug: 'palace-theatre-lore',
    description: 'Discover the original opening year of the historic Canton Palace Theatre.',
    instructions: 'Read the historic landmark brass shield beside the theater entrance doors. What year did the Palace Theatre open?',
    pointValue: 125,
    difficulty: 'easy',
    category: 'trivia',
    verificationType: 'passphrase',
    targetCode: '1927',
    proofRequirement: 'Type the 4-digit opening year.',
    isFlash: false,
    status: 'active',
    sortOrder: 6,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'qst-market-square-flash',
    eventId: SEED_EVENT.id,
    locationId: 'loc-centennial-plaza',
    location: SEED_LOCATIONS[0],
    title: '⚡ FLASH QUEST: Market Square Signal Drop',
    slug: 'market-square-flash',
    description: 'A pop-up signal has activated in Market Square! Check in before time runs out.',
    instructions: 'Confirm check-in near the Market Square pavilion during this active window.',
    pointValue: 250,
    difficulty: 'medium',
    category: 'flash',
    verificationType: 'checkin',
    proofRequirement: 'Rapid check-in verification.',
    isFlash: true,
    status: 'active',
    sortOrder: 7,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'qst-onesto-brass-motto',
    eventId: SEED_EVENT.id,
    locationId: 'loc-onesto-building',
    location: SEED_LOCATIONS[7],
    title: 'The Onesto Entrance Key',
    slug: 'onesto-brass-motto',
    description: 'Examine the entrance stonework above the historic Onesto entrance doors.',
    instructions: 'Find the capitalized single word inscribed in stone above the historic entrance transom. (Hint: "ONESTO")',
    pointValue: 150,
    difficulty: 'medium',
    category: 'observation',
    verificationType: 'passphrase',
    targetCode: 'ONESTO',
    proofRequirement: 'Enter the exact word found above the doorway.',
    isFlash: false,
    status: 'active',
    sortOrder: 8,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'qst-hof-legend-qr',
    eventId: SEED_EVENT.id,
    locationId: 'loc-hof-trail',
    location: SEED_LOCATIONS[6],
    title: 'Hall of Fame Trail Emblem',
    slug: 'hof-trail-emblem',
    description: 'Locate the Canton Quests football heritage QR emblem along the Hall of Fame city trail.',
    instructions: 'Scan the Canton Quests QR code on the marker pillar or enter the secret passcode.',
    pointValue: 400,
    difficulty: 'hard',
    category: 'trivia',
    verificationType: 'qr',
    targetCode: 'HOF-CANTON-LEGEND',
    proofRequirement: 'Scan or type passcode from the Hall of Fame Trail marker.',
    isFlash: false,
    status: 'active',
    sortOrder: 9,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'qst-secret-cipher-77',
    eventId: SEED_EVENT.id,
    locationId: 'loc-4th-st-mural',
    location: SEED_LOCATIONS[2],
    title: '🔒 SECRET QUEST: The 4th Street Cipher',
    slug: 'secret-cipher-77',
    description: 'Unlisted secret mission hidden deep in downtown Canton.',
    instructions: 'Decode the secret passphrase scattered across the Arts District markers to unlock 750 bonus XP!',
    pointValue: 750,
    difficulty: 'epic',
    category: 'secret',
    verificationType: 'passphrase',
    targetCode: 'CYPHER-77',
    proofRequirement: 'Enter the decoded master passphrase.',
    isFlash: false,
    status: 'active',
    sortOrder: 10,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'qst-plaza-fountain-photo',
    eventId: SEED_EVENT.id,
    locationId: 'loc-centennial-plaza',
    location: SEED_LOCATIONS[0],
    title: 'Plaza Water Feature Snap',
    slug: 'plaza-water-snap',
    description: 'Snap a fun photo showing the Centennial Plaza fountain jets or LED screen background.',
    instructions: 'Take a clear photo and submit it for visual verification.',
    pointValue: 100,
    difficulty: 'easy',
    category: 'photo_video',
    verificationType: 'photo',
    proofRequirement: 'Photo upload of Centennial Plaza fountain area.',
    isFlash: false,
    status: 'active',
    sortOrder: 11,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'qst-downtown-marquee-code',
    eventId: SEED_EVENT.id,
    locationId: 'loc-music-hall',
    location: SEED_LOCATIONS[5],
    title: 'Marquee Showtime Code',
    slug: 'marquee-showtime-code',
    description: 'Inspect the underside of the theater canopy for the secret 8-letter code.',
    instructions: 'Enter the word "SHOWTIME" after discovering the marquee plaque.',
    pointValue: 125,
    difficulty: 'medium',
    category: 'observation',
    verificationType: 'passphrase',
    targetCode: 'SHOWTIME',
    proofRequirement: 'Enter the passphrase found under the marquee.',
    isFlash: false,
    status: 'active',
    sortOrder: 12,
    createdAt: '2026-08-01T00:00:00Z',
  },
];

export const SEED_DEMO_PLAYERS: Player[] = [
  {
    id: 'plr-apex-hunter',
    displayName: 'ApexHunter_330',
    avatarUrl: '⚡',
    role: 'player',
    totalXp: 850,
    level: 4,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'plr-canton-rover',
    displayName: 'CantonRover',
    avatarUrl: '🧭',
    role: 'player',
    totalXp: 600,
    level: 3,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'plr-downtown-decoder',
    displayName: 'DowntownDecoder',
    avatarUrl: '🔍',
    role: 'player',
    totalXp: 450,
    level: 2,
    createdAt: '2026-08-01T00:00:00Z',
  },
];
