// Canton Quests — Phase 3 Test Seed Data (Canton, Ohio)

import {
  City,
  QuestEvent,
  LocationInfo,
  Quest,
  Player,
  Team,
  TeamMember,
  LiveAnnouncement,
  SecretCode,
  Collectible,
  NPCCharacter,
  BusinessPartnerInfo,
  CrowdObjective,
  BonusWindow,
  Prize,
} from './types';

export const SEED_CITY: City = {
  id: 'city-canton-oh',
  name: 'Canton',
  slug: 'canton-oh',
  state: 'OH',
  isActive: true,
  createdAt: '2026-08-01T00:00:00Z',
};

export const SEED_LOCATIONS: LocationInfo[] = [
  {
    id: 'loc-centennial-plaza',
    cityId: SEED_CITY.id,
    name: 'Centennial Plaza',
    address: '330 Market Ave N, Canton, OH 44702',
    latitude: 40.7989,
    longitude: -81.3748,
    locationNotes: 'Downtown Canton central gathering space with outdoor screens and cafe seating.',
    isPartner: true,
    radiusMeters: 60,
    accessNotes: 'Open public plaza 6:00 AM – 11:00 PM daily. High pedestrian zone.',
    openingHours: '6:00 AM - 11:00 PM',
  },
  {
    id: 'loc-mckinley-monument',
    cityId: SEED_CITY.id,
    name: 'McKinley National Memorial',
    address: '800 McKinley Monument Dr NW, Canton, OH 44708',
    latitude: 40.8064,
    longitude: -81.3933,
    locationNotes: 'Historic 108-step monument overlooking the park and city.',
    isPartner: false,
    radiusMeters: 80,
    accessNotes: 'Park grounds open dawn to dusk. Stairway can be slick in rainy weather.',
    openingHours: 'Dawn - Dusk',
  },
  {
    id: 'loc-4th-st-mural',
    cityId: SEED_CITY.id,
    name: '4th Street Arts Corridor Mural',
    address: '4th St NW & Court Ave NW, Canton, OH 44702',
    latitude: 40.7995,
    longitude: -81.3755,
    locationNotes: 'Vibrant street art wall in the heart of downtown Canton Arts District.',
    isPartner: true,
    radiusMeters: 50,
    accessNotes: 'Public sidewalk access 24/7. Watch for downtown vehicular traffic.',
    openingHours: '24/7 Public Access',
  },
  {
    id: 'loc-aura-craft-coffee',
    cityId: SEED_CITY.id,
    name: 'Aura Craft Coffee',
    address: '414 4th St NW, Canton, OH 44702',
    latitude: 40.7998,
    longitude: -81.3761,
    locationNotes: 'Local partner coffee shop. Look near the espresso counter or patio area.',
    isPartner: true,
    radiusMeters: 40,
    accessNotes: 'Indoor scanning during business hours (7 AM - 6 PM M-S). Patio access 24/7.',
    openingHours: '7:00 AM - 6:00 PM',
  },
  {
    id: 'loc-arcade-bar',
    cityId: SEED_CITY.id,
    name: 'Downtown Canton Arcade Vault',
    address: '218 Market Ave N, Canton, OH 44702',
    latitude: 40.7978,
    longitude: -81.3748,
    locationNotes: 'Retro arcade venue featuring vintage pinball and arcade cabinets.',
    isPartner: true,
    radiusMeters: 40,
    accessNotes: 'Family friendly hours 12 PM - 8 PM.',
    openingHours: '12:00 PM - 10:00 PM',
  },
  {
    id: 'loc-music-hall',
    cityId: SEED_CITY.id,
    name: 'Canton Palace Theatre',
    address: '605 Market Ave N, Canton, OH 44702',
    latitude: 40.8012,
    longitude: -81.3748,
    locationNotes: 'Historic theater marquee and architectural gem of Canton.',
    isPartner: true,
    radiusMeters: 50,
    accessNotes: 'Marquee visible from sidewalk 24/7.',
    openingHours: '24/7 Outdoor Access',
  },
  {
    id: 'loc-hof-trail',
    cityId: SEED_CITY.id,
    name: 'Hall of Fame City Marker',
    address: '2121 George Halas Dr NW, Canton, OH 44708',
    latitude: 40.8211,
    longitude: -81.3985,
    locationNotes: 'Commemorative plaza marker celebrating Canton football heritage.',
    isPartner: false,
    radiusMeters: 75,
    accessNotes: 'Outdoor trail plaza open daily.',
    openingHours: 'Dawn - Dusk',
  },
  {
    id: 'loc-onesto-building',
    cityId: SEED_CITY.id,
    name: 'The Onesto Historic Entrance',
    address: '225 2nd St NW, Canton, OH 44702',
    latitude: 40.7971,
    longitude: -81.3752,
    locationNotes: 'Grand historic hotel building with ornate brass entrance doors.',
    isPartner: false,
    radiusMeters: 45,
    accessNotes: 'Public sidewalk view.',
    openingHours: '24/7',
  },
];

export const SEED_EVENT: QuestEvent = {
  id: 'evt-canton-vol-1',
  cityId: SEED_CITY.id,
  title: 'Canton Quest Weekend #1 — The Founder’s Cipher',
  slug: 'canton-weekend-1',
  description:
    'Explore Canton, Ohio like never before! Decode urban ciphers, scan hidden QR codes, verify physical location proximity, and solve real-world mysteries across downtown Canton.',
  status: 'active',
  currentPhase: 'day_1',
  isPaused: false,
  startTime: '2026-09-04T18:00:00Z',
  endTime: '2026-09-07T22:00:00Z',
  basicInstructions:
    '1. Select any available quest below or view the Canton Map.\n2. Travel to the location in Canton.\n3. Verify GPS proximity or scan QR emblems.\n4. Earn XP, form teams, and top the leaderboard!',
  createdAt: '2026-08-01T00:00:00Z',
};

// Demo Players
export const SEED_DEMO_PLAYERS: Player[] = [
  {
    id: 'plr-apex-hunter',
    displayName: 'ApexHunter_330',
    avatarUrl: '⚡',
    role: 'player',
    totalXp: 850,
    level: 4,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'plr-canton-rover',
    displayName: 'CantonRover',
    avatarUrl: '🧭',
    role: 'player',
    totalXp: 600,
    level: 3,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'plr-downtown-decoder',
    displayName: 'DowntownDecoder',
    avatarUrl: '🔍',
    role: 'player',
    totalXp: 450,
    level: 2,
    createdAt: '2026-08-01T00:00:00Z',
  },
];

// Seed Teams
export const SEED_TEAMS: Team[] = [
  {
    id: 'team-canton-decoders',
    eventId: SEED_EVENT.id,
    name: 'Canton Cipher Syndicate',
    joinCode: 'CQ-7X9K',
    captainId: SEED_DEMO_PLAYERS[0].id,
    avatarSymbol: '🛡️',
    totalPoints: 1450,
    createdAt: '2026-08-07T18:30:00Z',
  },
  {
    id: 'team-market-st-rovers',
    eventId: SEED_EVENT.id,
    name: 'Market Square Rovers',
    joinCode: 'CQ-M420',
    captainId: SEED_DEMO_PLAYERS[1].id,
    avatarSymbol: '⚔️',
    totalPoints: 600,
    createdAt: '2026-08-07T19:00:00Z',
  },
];

export const SEED_TEAM_MEMBERS: TeamMember[] = [
  {
    id: 'tm-1',
    teamId: 'team-canton-decoders',
    playerId: SEED_DEMO_PLAYERS[0].id,
    joinedAt: '2026-08-07T18:30:00Z',
  },
  {
    id: 'tm-2',
    teamId: 'team-canton-decoders',
    playerId: SEED_DEMO_PLAYERS[2].id,
    joinedAt: '2026-08-07T18:45:00Z',
  },
  {
    id: 'tm-3',
    teamId: 'team-market-st-rovers',
    playerId: SEED_DEMO_PLAYERS[1].id,
    joinedAt: '2026-08-07T19:00:00Z',
  },
];

// Phase 3 Collectibles Catalog
export const SEED_COLLECTIBLES: Collectible[] = [
  {
    id: 'col-founder-token',
    name: 'Founder Token',
    slug: 'founder-token',
    description: 'Awarded to agents who crack the Founder Cipher at Centennial Plaza.',
    badgeSymbol: '🏅',
    rarity: 'common',
  },
  {
    id: 'col-cipher-fragment-1',
    name: 'Cipher Fragment Alpha',
    slug: 'cipher-fragment-1',
    description: 'First piece of the 3-part Canton Master Cipher.',
    badgeSymbol: '🧩',
    rarity: 'rare',
  },
  {
    id: 'col-cipher-fragment-2',
    name: 'Cipher Fragment Beta',
    slug: 'cipher-fragment-2',
    description: 'Second piece of the 3-part Canton Master Cipher.',
    badgeSymbol: '🧩',
    rarity: 'rare',
  },
  {
    id: 'col-cipher-fragment-3',
    name: 'Cipher Fragment Gamma',
    slug: 'cipher-fragment-3',
    description: 'Final piece of the 3-part Canton Master Cipher.',
    badgeSymbol: '🧩',
    rarity: 'legendary',
  },
  {
    id: 'col-palace-seal',
    name: 'Palace Theatre Golden Seal',
    slug: 'palace-seal',
    description: 'Historic seal granted for completing the Palace Theatre marquee lore.',
    badgeSymbol: '👑',
    rarity: 'legendary',
  },
];

// Phase 3 Secret Codes
export const SEED_SECRET_CODES: SecretCode[] = [
  {
    id: 'code-founder-2026',
    eventId: SEED_EVENT.id,
    code: '',
    description: 'Game Master Opening Broadcast Code',
    bonusPoints: 150,
    maxRedemptions: 50,
    currentRedemptions: 4,
    isActive: true,
    grantCollectibleId: 'col-founder-token',
    createdAt: '2026-08-07T18:00:00Z',
  },
  {
    id: 'code-courier-77',
    eventId: SEED_EVENT.id,
    code: '',
    description: 'Handed out by roaming NPC "The Courier" near Arts District',
    bonusPoints: 200,
    maxRedemptions: 15,
    currentRedemptions: 2,
    isActive: true,
    grantCollectibleId: 'col-palace-seal',
    createdAt: '2026-08-07T19:30:00Z',
  },
];

// Phase 3 Announcements
export const SEED_ANNOUNCEMENTS: LiveAnnouncement[] = [
  {
    id: 'ann-1',
    eventId: SEED_EVENT.id,
    title: '🎉 CANTON QUEST WEEKEND #1 IS LIVE!',
    message: 'Welcome Agents! Stand by for pop-up flash drops and secret code broadcasts.',
    urgency: 'urgent',
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'ann-2',
    eventId: SEED_EVENT.id,
    title: '🔥 DOUBLE XP ACTIVE ON PUZZLE QUESTS',
    message: 'All puzzle category quest completions earn 2x XP for the next 45 minutes!',
    urgency: 'flash',
    expiresAt: new Date(Date.now() + 45 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 900000).toISOString(),
  },
  {
    id: 'ann-3',
    eventId: SEED_EVENT.id,
    title: '🕵️ ROAMING NPC SPOTTED',
    message: '"The Courier" was last seen near the 4th Street Arts Corridor Mural with secret passphrase codes.',
    urgency: 'info',
    createdAt: new Date(Date.now() - 300000).toISOString(),
  },
];

// Phase 3 NPC Characters
export const SEED_NPCS: NPCCharacter[] = [
  {
    id: 'npc-courier',
    eventId: SEED_EVENT.id,
    aliasName: 'The Courier',
    description: 'A mysterious agent roaming downtown Canton handing out secret passphrase cards.',
    avatarSymbol: '🕵️',
    isActive: true,
    currentZone: '4th Street Arts Corridor',
    clueHint: 'Look near the giant street mural or Aura Craft Coffee patio.',
    secretCode: 'Distributed in person by The Courier',
    lastSpottedAt: new Date(Date.now() - 600000).toISOString(),
  },
];

// Phase 3 Business Partners
export const SEED_PARTNERS: BusinessPartnerInfo[] = [
  {
    id: 'bp-aura-coffee',
    cityId: SEED_CITY.id,
    name: 'Aura Craft Coffee',
    address: '414 4th St NW, Canton, OH 44702',
    contactNotes: 'Partner coffee shop providing QR card placement and perk discounts.',
    publicInstructions: 'Show completed quest screen at counter for 10% off espresso drinks!',
    isActive: true,
  },
  {
    id: 'bp-arcade-vault',
    cityId: SEED_CITY.id,
    name: 'Downtown Canton Arcade Vault',
    address: '218 Market Ave N, Canton, OH 44702',
    contactNotes: 'Arcade venue partner.',
    publicInstructions: 'Show completed quest screen for 5 free game tokens!',
    isActive: true,
  },
];

// Phase 3 Crowd Objectives
export const SEED_CROWD_OBJECTIVES: CrowdObjective[] = [
  {
    id: 'crowd-20-quests',
    eventId: SEED_EVENT.id,
    title: 'Canton Collective: 20 Citywide Quest Solves',
    description: 'When players collectively complete 20 quests, a secret bonus drop unlocks!',
    targetCount: 20,
    currentCount: 14,
    objectiveType: 'total_completions',
    isAchieved: false,
  },
];

// Phase 3 Bonus Windows
export const SEED_BONUS_WINDOWS: BonusWindow[] = [
  {
    id: 'bw-puzzle-2x',
    eventId: SEED_EVENT.id,
    title: 'Double XP Puzzle Sprint',
    multiplier: 2.0,
    flatBonus: 0,
    targetCategory: 'puzzle',
    startsAt: new Date(Date.now() - 900000).toISOString(),
    expiresAt: new Date(Date.now() + 45 * 60 * 1000).toISOString(),
    isActive: false,
  },
];

// Phase 3 Demo Prizes
export const SEED_PRIZES: Prize[] = [
  {
    id: 'prz-1',
    eventId: SEED_EVENT.id,
    title: '🏆 Canton Quest Champion Trophy & $100 Local Gift Pass',
    sponsorName: 'Downtown Canton Partnership',
    quantity: 1,
    eligibilityRule: 'Highest overall XP score at Finale',
  },
  {
    id: 'prz-2',
    eventId: SEED_EVENT.id,
    title: '☕ Year of Aura Coffee VIP Pass',
    sponsorName: 'Aura Craft Coffee',
    quantity: 1,
    eligibilityRule: 'Winner of Business Partner Trail Challenge',
  },
];

// Exact SEED_QUESTS array order preserved with Phase 3 fields added
export const SEED_QUESTS: Quest[] = [
  {
    id: 'qst-centennial-discovery',
    eventId: SEED_EVENT.id,
    locationId: 'loc-centennial-plaza',
    location: SEED_LOCATIONS[0],
    title: 'Centennial Beacon Check-In',
    slug: 'centennial-beacon',
    description: 'Reach Centennial Plaza in downtown Canton and initialize your field scanner.',
    instructions: 'Stand anywhere near the central lawn at Centennial Plaza and tap the check-in scanner.',
    pointValue: 50,
    difficulty: 'easy',
    category: 'exploration',
    verificationType: 'checkin',
    proofRequirement: 'Confirm physical check-in at Centennial Plaza.',
    isFlash: false,
    status: 'active',
    sortOrder: 1,
    createdAt: '2026-08-01T00:00:00Z',
    radiusMeters: 60,
  },
  {
    id: 'qst-mckinley-cipher',
    eventId: SEED_EVENT.id,
    locationId: 'loc-mckinley-monument',
    location: SEED_LOCATIONS[1],
    title: 'The McKinley Monument Year',
    slug: 'mckinley-monument-year',
    description: 'Find the dedication year engraved on the bronze cornerstone of the McKinley Memorial.',
    instructions: 'Locate the historic bronze plaque near the monument stairs entrance and enter the 4-digit dedication year.',
    pointValue: 150,
    difficulty: 'medium',
    category: 'puzzle',
    verificationType: 'passphrase',
    proofRequirement: 'Enter the 4-digit year found on the cornerstone plaque.',
    isFlash: false,
    status: 'active',
    sortOrder: 2,
    createdAt: '2026-08-01T00:00:00Z',
    radiusMeters: 80,
  },
  {
    id: 'qst-4th-st-mural-photo',
    eventId: SEED_EVENT.id,
    locationId: 'loc-4th-st-mural',
    location: SEED_LOCATIONS[2],
    title: 'Mural Pose Challenge',
    slug: '4th-st-mural-pose',
    description: 'Recreate a high-energy victory pose with the giant Arts District street mural.',
    instructions: 'Take a photo of yourself or your team posing in front of the 4th Street mural. Upload the picture for review.',
    pointValue: 200,
    difficulty: 'medium',
    category: 'creative',
    verificationType: 'photo',
    proofRequirement: 'Upload a photo showing team members in front of the mural.',
    isFlash: false,
    status: 'active',
    sortOrder: 3,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'qst-aura-coffee-qr',
    eventId: SEED_EVENT.id,
    locationId: 'loc-aura-craft-coffee',
    location: SEED_LOCATIONS[3],
    title: 'Aura Brew Frequency',
    slug: 'aura-coffee-scan',
    description: 'Scan the official Canton Quests QR code displayed inside Aura Craft Coffee.',
    instructions: 'Find the Canton Quests QR card near the counter at Aura Craft Coffee and scan it with your camera or enter the code.',
    pointValue: 100,
    difficulty: 'easy',
    category: 'business_partner',
    verificationType: 'qr',
    proofRequirement: 'Scan or type the QR code passphrase displayed at Aura Craft Coffee.',
    isFlash: false,
    status: 'active',
    sortOrder: 4,
    createdAt: '2026-08-01T00:00:00Z',
    radiusMeters: 40,
    requireQrAndLocation: true,
  },
  {
    id: 'qst-arcade-high-score-video',
    eventId: SEED_EVENT.id,
    locationId: 'loc-arcade-bar',
    location: SEED_LOCATIONS[4],
    title: 'Arcade Champion High-Five',
    slug: 'arcade-champion-video',
    description: 'Record a short 5-second celebratory video at the Arcade Vault.',
    instructions: 'Capture a quick clip of your team cheering or high-fiving in front of a pinball machine or classic arcade machine.',
    pointValue: 350,
    difficulty: 'hard',
    category: 'photo_video',
    verificationType: 'video',
    proofRequirement: 'Upload a short video clip (or video link) showing your arcade celebration.',
    isFlash: false,
    status: 'active',
    sortOrder: 5,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'qst-palace-theatre-year',
    eventId: SEED_EVENT.id,
    locationId: 'loc-music-hall',
    location: SEED_LOCATIONS[5],
    title: 'Canton Palace Marquee Lore',
    slug: 'palace-theatre-lore',
    description: 'Discover the original opening year of the historic Canton Palace Theatre.',
    instructions: 'Read the historic landmark brass shield beside the theater entrance doors. What year did the Palace Theatre open?',
    pointValue: 125,
    difficulty: 'easy',
    category: 'trivia',
    verificationType: 'passphrase',
    proofRequirement: 'Type the 4-digit opening year.',
    isFlash: false,
    status: 'active',
    sortOrder: 6,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'qst-market-square-flash',
    eventId: SEED_EVENT.id,
    locationId: 'loc-centennial-plaza',
    location: SEED_LOCATIONS[0],
    title: '⚡ FLASH QUEST: Market Square Signal Drop',
    slug: 'market-square-flash',
    description: 'A pop-up signal has activated in Market Square! Check in before time runs out.',
    instructions: 'Confirm check-in near the Market Square pavilion during this active window.',
    pointValue: 250,
    difficulty: 'medium',
    category: 'flash',
    verificationType: 'checkin',
    proofRequirement: 'Rapid check-in verification.',
    isFlash: true,
    startsAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 45 * 60 * 1000).toISOString(),
    status: 'active',
    sortOrder: 7,
    createdAt: '2026-08-01T00:00:00Z',
    radiusMeters: 60,
  },
  {
    id: 'qst-onesto-brass-motto',
    eventId: SEED_EVENT.id,
    locationId: 'loc-onesto-building',
    location: SEED_LOCATIONS[7],
    title: 'The Onesto Entrance Key',
    slug: 'onesto-brass-motto',
    description: 'Examine the entrance stonework above the historic Onesto entrance doors.',
    instructions: 'Find the capitalized single word inscribed in stone above the historic entrance transom.',
    pointValue: 150,
    difficulty: 'medium',
    category: 'observation',
    verificationType: 'passphrase',
    proofRequirement: 'Enter the exact word found above the doorway.',
    isFlash: false,
    status: 'active',
    sortOrder: 8,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'qst-hof-legend-qr',
    eventId: SEED_EVENT.id,
    locationId: 'loc-hof-trail',
    location: SEED_LOCATIONS[6],
    title: 'Hall of Fame Trail Emblem',
    slug: 'hof-trail-emblem',
    description: 'Locate the Canton Quests football heritage QR emblem along the Hall of Fame city trail.',
    instructions: 'Scan the Canton Quests QR code on the marker pillar or enter the secret passcode.',
    pointValue: 400,
    difficulty: 'hard',
    category: 'trivia',
    verificationType: 'qr',
    proofRequirement: 'Scan or type passcode from the Hall of Fame Trail marker.',
    isFlash: false,
    status: 'active',
    sortOrder: 9,
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'qst-secret-cipher-77',
    eventId: SEED_EVENT.id,
    locationId: 'loc-4th-st-mural',
    location: SEED_LOCATIONS[2],
    title: '🔒 SECRET QUEST: The 4th Street Cipher',
    slug: 'secret-cipher-77',
    description: 'Unlisted secret mission hidden deep in downtown Canton.',
    instructions: 'Decode the secret passphrase scattered across the Arts District markers to unlock 750 bonus XP!',
    pointValue: 750,
    difficulty: 'epic',
    category: 'secret',
    verificationType: 'passphrase',
    proofRequirement: 'Enter the decoded master passphrase.',
    isFlash: false,
    status: 'active',
    sortOrder: 10,
    createdAt: '2026-08-01T00:00:00Z',
    isSecret: true,
  },
  {
    id: 'qst-founders-secret-clue',
    eventId: SEED_EVENT.id,
    locationId: 'loc-centennial-plaza',
    location: SEED_LOCATIONS[0],
    title: 'The Founder’s Clue (Chain Step 2)',
    slug: 'founders-secret-clue',
    description: 'Unlocked by completing Centennial Beacon! Search the bronze cornerstone near the plaza screen.',
    instructions: 'Enter the single secret word inscribed on the Founder plaque.',
    pointValue: 150,
    difficulty: 'medium',
    category: 'puzzle',
    verificationType: 'passphrase',
    proofRequirement: 'Enter the passphrase found on the Founder plaque.',
    isFlash: false,
    status: 'active',
    sortOrder: 11,
    createdAt: '2026-08-01T00:00:00Z',
    radiusMeters: 60,
    prerequisiteQuestId: 'qst-centennial-discovery',
    unlockConditionType: 'prerequisite',
  },
  {
    id: 'qst-palace-flash-popup',
    eventId: SEED_EVENT.id,
    locationId: 'loc-music-hall',
    location: SEED_LOCATIONS[5],
    title: '⚡ FLASH DROP: Palace Marquee Midnight Cipher',
    slug: 'palace-marquee-flash',
    description: 'Game Master pop-up mission! Inspect the Palace Theatre marquee under lights.',
    instructions: 'Enter the flash passcode before time expires.',
    pointValue: 300,
    difficulty: 'hard',
    category: 'flash',
    verificationType: 'passphrase',
    proofRequirement: 'Enter flash passcode before expiry.',
    isFlash: true,
    startsAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 20 * 60 * 1000).toISOString(),
    status: 'active',
    sortOrder: 12,
    createdAt: '2026-08-01T00:00:00Z',
  },
  // Phase 3 Finale Quest
  {
    id: 'qst-grand-finale-cipher',
    eventId: SEED_EVENT.id,
    locationId: 'loc-centennial-plaza',
    location: SEED_LOCATIONS[0],
    title: '🏆 GRAND FINALE: The Canton Founder’s Master Key',
    slug: 'grand-finale-cipher',
    description: 'The ultimate finale quest! Available only to qualified agents during Finale Mode.',
    instructions: 'Enter the final master key to claim finale points!',
    pointValue: 1000,
    difficulty: 'epic',
    category: 'finale',
    verificationType: 'passphrase',
    proofRequirement: 'Finale qualification required.',
    isFlash: false,
    isFinaleQuest: true,
    status: 'active',
    sortOrder: 13,
    createdAt: '2026-08-01T00:00:00Z',
  },
];
