// Canton Quests — Phase 3 Test Seed Data (Canton, Ohio)

import {
  City,
  QuestEvent,
  LocationInfo,
  Quest,
  Player,
  LiveAnnouncement,
  SecretCode,
  Collectible,
  Achievement,
  NPCCharacter,
  BusinessPartnerInfo,
  CrowdObjective,
  BonusWindow,
  Prize,
} from './types';

export const SEED_CITY: City = {
  id: 'city-canton-oh',
  name: 'Canton',
  slug: 'canton-oh',
  state: 'OH',
  isActive: true,
  createdAt: '2026-08-01T00:00:00Z',
};

export const SEED_LOCATIONS: LocationInfo[] = [
  {
    id: 'loc-centennial-plaza',
    cityId: SEED_CITY.id,
    name: 'Centennial Plaza',
    address: '330 Market Ave N, Canton, OH 44702',
    latitude: 40.7989,
    longitude: -81.3748,
    locationNotes: 'Downtown Canton central gathering space with outdoor screens and cafe seating.',
    isPartner: true,
    radiusMeters: 60,
    accessNotes: 'Open public plaza 6:00 AM – 11:00 PM daily. High pedestrian zone.',
    openingHours: '6:00 AM - 11:00 PM',
  },
  {
    id: 'loc-mckinley-monument',
    cityId: SEED_CITY.id,
    name: 'McKinley National Memorial',
    address: '800 McKinley Monument Dr NW, Canton, OH 44708',
    latitude: 40.8064,
    longitude: -81.3933,
    locationNotes: 'Historic 108-step monument overlooking the park and city.',
    isPartner: false,
    radiusMeters: 80,
    accessNotes: 'Park grounds open dawn to dusk. Stairway can be slick in rainy weather.',
    openingHours: 'Dawn - Dusk',
  },
  {
    id: 'loc-4th-st-mural',
    cityId: SEED_CITY.id,
    name: '4th Street Arts Corridor Mural',
    address: '4th St NW & Court Ave NW, Canton, OH 44702',
    latitude: 40.7995,
    longitude: -81.3755,
    locationNotes: 'Vibrant street art wall in the heart of downtown Canton Arts District.',
    isPartner: true,
    radiusMeters: 50,
    accessNotes: 'Public sidewalk access 24/7. Watch for downtown vehicular traffic.',
    openingHours: '24/7 Public Access',
  },
  {
    id: 'loc-aura-craft-coffee',
    cityId: SEED_CITY.id,
    name: 'Aura Craft Coffee',
    address: '414 4th St NW, Canton, OH 44702',
    latitude: 40.7998,
    longitude: -81.3761,
    locationNotes: 'Local partner coffee shop. Look near the espresso counter or patio area.',
    isPartner: true,
    radiusMeters: 40,
    accessNotes: 'Indoor scanning during business hours (7 AM - 6 PM M-S). Patio access 24/7.',
    openingHours: '7:00 AM - 6:00 PM',
  },
  {
    id: 'loc-arcade-bar',
    cityId: SEED_CITY.id,
    name: 'Downtown Canton Arcade Vault',
    address: '218 Market Ave N, Canton, OH 44702',
    latitude: 40.7978,
    longitude: -81.3748,
    locationNotes: 'Retro arcade venue featuring vintage pinball and arcade cabinets.',
    isPartner: true,
    radiusMeters: 40,
    accessNotes: 'Family friendly hours 12 PM - 8 PM.',
    openingHours: '12:00 PM - 10:00 PM',
  },
  {
    id: 'loc-music-hall',
    cityId: SEED_CITY.id,
    name: 'Canton Palace Theatre',
    address: '605 Market Ave N, Canton, OH 44702',
    latitude: 40.8012,
    longitude: -81.3748,
    locationNotes: 'Historic theater marquee and architectural gem of Canton.',
    isPartner: true,
    radiusMeters: 50,
    accessNotes: 'Marquee visible from sidewalk 24/7.',
    openingHours: '24/7 Outdoor Access',
  },
  {
    id: 'loc-hof-trail',
    cityId: SEED_CITY.id,
    name: 'Hall of Fame City Marker',
    address: '2121 George Halas Dr NW, Canton, OH 44708',
    latitude: 40.8211,
    longitude: -81.3985,
    locationNotes: 'Commemorative plaza marker celebrating Canton football heritage.',
    isPartner: false,
    radiusMeters: 75,
    accessNotes: 'Outdoor trail plaza open daily.',
    openingHours: 'Dawn - Dusk',
  },
  {
    id: 'loc-onesto-building',
    cityId: SEED_CITY.id,
    name: 'The Onesto Historic Entrance',
    address: '225 2nd St NW, Canton, OH 44702',
    latitude: 40.7971,
    longitude: -81.3752,
    locationNotes: 'Grand historic hotel building with ornate brass entrance doors.',
    isPartner: false,
    radiusMeters: 45,
    accessNotes: 'Public sidewalk view.',
    openingHours: '24/7',
  },
  {
    id: 'loc-mother-goose-land',
    cityId: SEED_CITY.id,
    name: 'Mother Goose Land',
    address: '714 12th St NW, Canton, OH 44703',
    latitude: 40.8055,
    longitude: -81.3862,
    locationNotes: 'Historic Canton park featuring large illustrated mural walls and nostalgic storybook character landmarks.',
    isPartner: false,
    radiusMeters: 60,
    accessNotes: 'Open public park. Daylight hours recommended. Check current seasonal operating status before visiting.',
    openingHours: 'Dawn - Dusk (seasonal)',
  },
  {
    id: 'loc-west-lawn-frankenstein',
    cityId: SEED_CITY.id,
    name: 'Frankenstein Monument at West Lawn Cemetery',
    address: '1919 7th St NW, Canton, OH 44708',
    locationNotes:
      'Human field verification required before launch: confirm exact monument location, cemetery visitor rules, and any photography restrictions with West Lawn Cemetery staff.',
    isPartner: false,
    radiusMeters: 60,
    accessNotes:
      'Daylight cemetery visit only during posted visitor hours. Stay on cemetery paths and roads, keep voices low, and never touch, climb, lean on, decorate, or disturb graves, monuments, markers, flowers, or memorial items.',
    openingHours: 'Posted visitor hours only; daylight access. Gates may close earlier in winter. Reconfirm before launch.',
  },
];

export const SEED_EVENT: QuestEvent = {
  id: 'evt-canton-vol-1',
  cityId: SEED_CITY.id,
  title: "Canton Quests: Volume 1 - The Founder's Cipher",
  slug: 'canton-weekend-1',
  description:
    'A real-world Canton adventure of founder marks, hidden field signals, public art, history nodes, partner stops, and one respectful cemetery mystery.',
  status: 'active',
  currentPhase: 'day_1',
  isPaused: false,
  startTime: '2026-09-11T18:00:00Z',
  endTime: '2026-09-14T22:00:00Z',
  basicInstructions:
    '1. Choose a mission from the board.\n2. Travel only to public or partner-approved places during posted hours.\n3. Use the on-site clue, QR, photo, or GPS check to submit proof.\n4. Earn XP and drawing entries, then check progress and the leaderboard.',
  safetyNotes:
    'Use marked crosswalks, obey posted hours, avoid private property, and skip any location that feels unsafe or unavailable. Cemetery quests are daylight-only and require respectful conduct.',
  mapCenterLat: 40.7989,
  mapCenterLon: -81.3748,
  themeColor: '#f5b942',
  createdAt: '2026-08-01T00:00:00Z',
};

// Demo Players with Path & Attribution Metadata
export const SEED_DEMO_PLAYERS: Player[] = [
  {
    id: 'plr-apex-hunter',
    displayName: 'ApexHunter_330',
    avatarUrl: '⚡',
    role: 'player',
    totalXp: 850,
    level: 4,
    selectedStartingPath: 'challenge',
    acquisitionSource: 'challenge_flyer',
    tagline: 'Leaderboard chaser. Speed and ciphers.',
    favoriteStyle: 'Speed & Physical Challenge',
    themeColor: '#ef4444',
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'plr-canton-rover',
    displayName: 'CantonRover',
    avatarUrl: '🧭',
    role: 'player',
    totalXp: 600,
    level: 3,
    selectedStartingPath: 'family',
    acquisitionSource: 'family_flyer',
    tagline: 'Exploring Canton landmarks with the crew.',
    favoriteStyle: 'Arts & History',
    themeColor: '#f59e0b',
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'plr-downtown-decoder',
    displayName: 'DowntownDecoder',
    avatarUrl: '🔍',
    role: 'player',
    totalXp: 450,
    level: 2,
    selectedStartingPath: 'secret',
    acquisitionSource: 'secret_flyer',
    tagline: 'Ciphers, history, and forgotten lore.',
    favoriteStyle: 'Cryptic Mystery',
    themeColor: '#8b5cf6',
    createdAt: '2026-08-01T00:00:00Z',
  },
];

// Canonical Achievements Catalog
export const SEED_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'ach-pathfinder-family',
    slug: 'pathfinder-family',
    name: 'Pathfinder: Family Adventure',
    description: 'Completed your first mission starting in the Downtown Arts district.',
    badgeSymbol: '🧭',
    category: 'path',
    rarity: 'common',
    district: 'family',
  },
  {
    id: 'ach-pathfinder-challenge',
    slug: 'pathfinder-challenge',
    name: 'Pathfinder: Kinetic Challenge',
    description: 'Completed your first mission starting in the Challenge district.',
    badgeSymbol: '⚡',
    category: 'path',
    rarity: 'common',
    district: 'challenge',
  },
  {
    id: 'ach-pathfinder-secret',
    slug: 'pathfinder-secret',
    name: 'Pathfinder: Secret Mystery',
    description: 'Completed your first mission starting in the Mystery & Memorial district.',
    badgeSymbol: '🗝️',
    category: 'path',
    rarity: 'common',
    district: 'secret',
  },
  {
    id: 'ach-district-sweep-family',
    slug: 'district-sweep-family',
    name: 'District Sweep: Arts & Downtown',
    description: 'Completed all active missions in the Downtown Arts district.',
    badgeSymbol: '🎨',
    category: 'district',
    rarity: 'rare',
    district: 'family',
  },
  {
    id: 'ach-district-sweep-challenge',
    slug: 'district-sweep-challenge',
    name: 'District Sweep: Athletic & Skill',
    description: 'Completed all active missions in the Challenge district.',
    badgeSymbol: '🏆',
    category: 'district',
    rarity: 'rare',
    district: 'challenge',
  },
  {
    id: 'ach-district-sweep-secret',
    slug: 'district-sweep-secret',
    name: 'District Sweep: Mystery & Memorial',
    description: 'Completed all active missions in the Secret district.',
    badgeSymbol: '📜',
    category: 'district',
    rarity: 'rare',
    district: 'secret',
  },
  {
    id: 'ach-triple-threat',
    slug: 'triple-threat',
    name: 'Triple Threat',
    description: 'Completed qualifying missions across all three Canton districts (Family, Challenge, and Secret).',
    badgeSymbol: '🔱',
    category: 'exploration',
    rarity: 'epic',
  },
  {
    id: 'ach-nomad',
    slug: 'nomad',
    name: 'City Nomad',
    description: 'Completed qualifying missions across all three districts within the same event day.',
    badgeSymbol: '🌐',
    category: 'exploration',
    rarity: 'epic',
  },
  {
    id: 'ach-day-one-king',
    slug: 'day-one-king',
    name: 'Day 1 City Conqueror',
    description: 'Finished Day 1 ranked #1 in XP on the official individual leaderboard (+5 Prize Entries).',
    badgeSymbol: '👑',
    category: 'competitive',
    rarity: 'legendary',
  },
];

// Phase 3 Collectibles Catalog
export const SEED_COLLECTIBLES: Collectible[] = [
  {
    id: 'col-founder-token',
    name: 'Founder Token',
    slug: 'founder-token',
    description: 'Awarded to agents who crack the Founder Cipher at Centennial Plaza.',
    badgeSymbol: '🏅',
    rarity: 'common',
  },
  {
    id: 'col-cipher-fragment-1',
    name: 'Cipher Fragment Alpha',
    slug: 'cipher-fragment-1',
    description: 'First piece of the 3-part Canton Master Cipher.',
    badgeSymbol: '🧩',
    rarity: 'rare',
  },
  {
    id: 'col-cipher-fragment-2',
    name: 'Cipher Fragment Beta',
    slug: 'cipher-fragment-2',
    description: 'Second piece of the 3-part Canton Master Cipher.',
    badgeSymbol: '🧩',
    rarity: 'rare',
  },
  {
    id: 'col-cipher-fragment-3',
    name: 'Cipher Fragment Gamma',
    slug: 'cipher-fragment-3',
    description: 'Final piece of the 3-part Canton Master Cipher.',
    badgeSymbol: '🧩',
    rarity: 'legendary',
  },
  {
    id: 'col-palace-seal',
    name: 'Palace Theatre Golden Seal',
    slug: 'palace-seal',
    description: 'Historic seal granted for completing the Palace Theatre marquee lore.',
    badgeSymbol: '👑',
    rarity: 'legendary',
  },
];

// Phase 3 Secret Codes
export const SEED_SECRET_CODES: SecretCode[] = [
  {
    id: 'code-founder-2026',
    eventId: SEED_EVENT.id,
    code: '',
    description: 'Game Master Opening Broadcast Code',
    bonusPoints: 150,
    maxRedemptions: 50,
    currentRedemptions: 4,
    isActive: true,
    grantCollectibleId: 'col-founder-token',
    createdAt: '2026-08-07T18:00:00Z',
  },
  {
    id: 'code-courier-77',
    eventId: SEED_EVENT.id,
    code: '',
    description: 'Handed out by roaming NPC "The Courier" near Arts District',
    bonusPoints: 200,
    maxRedemptions: 15,
    currentRedemptions: 2,
    isActive: true,
    grantCollectibleId: 'col-palace-seal',
    createdAt: '2026-08-07T19:30:00Z',
  },
];

// Phase 3 Announcements
export const SEED_ANNOUNCEMENTS: LiveAnnouncement[] = [
  {
    id: 'ann-1',
    eventId: SEED_EVENT.id,
    title: '🎉 CANTON QUEST WEEKEND #1 IS LIVE!',
    message: 'Welcome Agents! Stand by for pop-up flash drops and secret code broadcasts.',
    urgency: 'urgent',
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'ann-2',
    eventId: SEED_EVENT.id,
    title: '🔥 DOUBLE XP ACTIVE ON PUZZLE QUESTS',
    message: 'All puzzle category quest completions earn 2x XP for the next 45 minutes!',
    urgency: 'flash',
    expiresAt: new Date(Date.now() + 45 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 900000).toISOString(),
  },
  {
    id: 'ann-3',
    eventId: SEED_EVENT.id,
    title: '🕵️ ROAMING NPC SPOTTED',
    message: '"The Courier" was last seen near the 4th Street Arts Corridor Mural with secret passphrase codes.',
    urgency: 'info',
    createdAt: new Date(Date.now() - 300000).toISOString(),
  },
];

// Phase 3 NPC Characters
export const SEED_NPCS: NPCCharacter[] = [
  {
    id: 'npc-courier',
    eventId: SEED_EVENT.id,
    aliasName: 'The Courier',
    description: 'A mysterious agent roaming downtown Canton handing out secret passphrase cards.',
    avatarSymbol: '🕵️',
    isActive: true,
    currentZone: '4th Street Arts Corridor',
    clueHint: 'Look near the giant street mural or Aura Craft Coffee patio.',
    secretCode: 'Distributed in person by The Courier',
    lastSpottedAt: new Date(Date.now() - 600000).toISOString(),
  },
];

// Phase 3 Business Partners
export const SEED_PARTNERS: BusinessPartnerInfo[] = [
  {
    id: 'bp-aura-coffee',
    cityId: SEED_CITY.id,
    name: 'Aura Craft Coffee',
    address: '414 4th St NW, Canton, OH 44702',
    contactNotes: 'Partner coffee shop providing QR card placement and perk discounts.',
    publicInstructions: 'Show completed quest screen at counter for 10% off espresso drinks!',
    isActive: true,
  },
  {
    id: 'bp-arcade-vault',
    cityId: SEED_CITY.id,
    name: 'Downtown Canton Arcade Vault',
    address: '218 Market Ave N, Canton, OH 44702',
    contactNotes: 'Arcade venue partner.',
    publicInstructions: 'Show completed quest screen for 5 free game tokens!',
    isActive: true,
  },
];

// Phase 3 Crowd Objectives
export const SEED_CROWD_OBJECTIVES: CrowdObjective[] = [
  {
    id: 'crowd-20-quests',
    eventId: SEED_EVENT.id,
    title: 'Canton Collective: 20 Citywide Quest Solves',
    description: 'When players collectively complete 20 quests, a secret bonus drop unlocks!',
    targetCount: 20,
    currentCount: 14,
    objectiveType: 'total_completions',
    isAchieved: false,
  },
];

// Phase 3 Bonus Windows
export const SEED_BONUS_WINDOWS: BonusWindow[] = [
  {
    id: 'bw-puzzle-2x',
    eventId: SEED_EVENT.id,
    title: 'Double XP Puzzle Sprint',
    multiplier: 2.0,
    flatBonus: 0,
    targetCategory: 'puzzle',
    startsAt: new Date(Date.now() - 900000).toISOString(),
    expiresAt: new Date(Date.now() + 45 * 60 * 1000).toISOString(),
    isActive: false,
  },
];

// Phase 3 Demo Prizes
export const SEED_PRIZES: Prize[] = [
  {
    id: 'prz-1',
    eventId: SEED_EVENT.id,
    title: '🏆 Canton Quest Champion Trophy & $100 Local Gift Pass',
    sponsorName: 'Downtown Canton Partnership',
    quantity: 1,
    eligibilityRule: 'Highest overall XP score at Finale',
  },
  {
    id: 'prz-2',
    eventId: SEED_EVENT.id,
    title: '☕ Year of Aura Coffee VIP Pass',
    sponsorName: 'Aura Craft Coffee',
    quantity: 1,
    eligibilityRule: 'Winner of Business Partner Trail Challenge',
  },
];

// Exact SEED_QUESTS array order preserved with Phase 3 fields added
export const SEED_QUESTS: Quest[] = [
  {
    id: 'qst-centennial-discovery',
    eventId: SEED_EVENT.id,
    locationId: 'loc-centennial-plaza',
    location: SEED_LOCATIONS[0],
    title: 'Open the Founder Signal',
    slug: 'centennial-beacon',
    description: "Every agent's first move. The city grid goes live the moment you arrive.",
    instructions: 'Report to Centennial Plaza and activate your field log. Tap CHECK IN when you are physically at the plaza. Your GPS will confirm the lock.',
    pointValue: 75,
    xpReward: 75,
    drawingEntryReward: 1,
    difficulty: 'easy',
    category: 'exploration',
    startingPath: 'family',
    verificationType: 'checkin',
    proofRequirement: 'GPS check-in from the public plaza area.',
    isFlash: false,
    status: 'active',
    sortOrder: 1,
    createdAt: '2026-08-01T00:00:00Z',
    radiusMeters: 60,
    requireLocationVerification: true,
    safetyNotes: 'Use public sidewalks and plaza areas. Do not enter closed event setups, stages, or restricted maintenance areas.',
    gmNotes: 'Field verify plaza access on launch weekend and place opening signage where it does not obstruct pedestrian flow.',
  },
  {
    id: 'qst-mckinley-cipher',
    eventId: SEED_EVENT.id,
    locationId: 'loc-mckinley-monument',
    location: SEED_LOCATIONS[1],
    title: 'The Stone Stair Cipher',
    slug: 'mckinley-monument-year',
    description: 'The McKinley Memorial has been carved with the answer since it was built. You just have to read it.',
    instructions: 'Visit the McKinley National Memorial during daylight public hours. Find the dedication marker near the monument approach. The year is on stone, facing the path — it marks when something was dedicated, not a birth or death year. Stand at the base of the stairs and look at the markers around you. Enter the four-digit year.',
    pointValue: 150,
    xpReward: 150,
    drawingEntryReward: 1,
    difficulty: 'medium',
    category: 'puzzle',
    startingPath: 'secret',
    verificationType: 'passphrase',
    proofRequirement: 'Enter the four-digit year found on the physical marker identified by the quest.',
    isFlash: false,
    status: 'active',
    sortOrder: 2,
    createdAt: '2026-08-01T00:00:00Z',
    radiusMeters: 80,
    requireLocationVerification: true,
    safetyNotes: 'Daylight recommended. Stairs may be slick; players do not need to climb quickly or leave public paths.',
    gmNotes: 'Existing server hash expects the verified four-digit answer. Reconfirm plaque wording and target marker before printing clue cards.',
  },
  {
    id: 'qst-4th-st-mural-photo',
    eventId: SEED_EVENT.id,
    locationId: 'loc-4th-st-mural',
    location: SEED_LOCATIONS[2],
    title: 'The Painted Witness',
    slug: '4th-st-mural-pose',
    description: 'The Arts District keeps its own records. Your job is to prove you read them.',
    instructions: 'Find the large street mural on 4th Street NW. Stand on the public sidewalk — the mural faces the street and is impossible to miss. Keep storefronts clear and watch traffic when crossing. Take a photo of your team or callsign card with the mural clearly visible behind you.',
    pointValue: 175,
    xpReward: 175,
    drawingEntryReward: 1,
    difficulty: 'medium',
    category: 'creative',
    startingPath: 'family',
    verificationType: 'photo',
    proofRequirement: 'Upload a photo or proof link showing the mural and your team/callsign card.',
    isFlash: false,
    status: 'active',
    sortOrder: 3,
    createdAt: '2026-08-01T00:00:00Z',
    safetyNotes: 'Stay on sidewalks, keep storefront entrances clear, and watch traffic when crossing downtown streets.',
    gmNotes: 'Manual review should verify the mural is visible and the proof appears original to the event window.',
  },
  {
    id: 'qst-aura-coffee-qr',
    eventId: SEED_EVENT.id,
    locationId: 'loc-aura-craft-coffee',
    location: SEED_LOCATIONS[3],
    title: 'The Counter-Sign at Aura',
    slug: 'aura-coffee-scan',
    description: 'A partner business is holding a signal for you. No purchase required.',
    instructions: 'Visit Aura Craft Coffee at 414 4th St NW during business hours (7 AM – 6 PM). Look near the espresso counter for the official Canton Quests QR card displaying the Canton Quests emblem. Scan or copy the passcode printed on it and enter it below.',
    pointValue: 125,
    xpReward: 125,
    drawingEntryReward: 1,
    difficulty: 'easy',
    category: 'business_partner',
    startingPath: 'family',
    verificationType: 'qr',
    proofRequirement: 'Enter the QR passcode displayed on the official Canton Quests card.',
    isFlash: false,
    status: 'active',
    sortOrder: 4,
    createdAt: '2026-08-01T00:00:00Z',
    radiusMeters: 40,
    requireQrAndLocation: true,
    safetyNotes: 'Visit only during partner-approved hours, respect staff and customers, and do not block the counter.',
    gmNotes: 'Requires partner permission, final QR placement, and free no-purchase access path before launch.',
  },
  {
    id: 'qst-arcade-high-score-video',
    eventId: SEED_EVENT.id,
    locationId: 'loc-arcade-bar',
    location: SEED_LOCATIONS[4],
    title: 'The Neon Victory Loop',
    slug: 'arcade-champion-video',
    description: 'A high-energy partner media quest. Partner confirmation required before activation.',
    instructions: 'When the partner site is confirmed and announced, visit the arcade venue during approved hours. Record a short celebration clip from the approved game area and upload it as proof.',
    pointValue: 250,
    xpReward: 250,
    drawingEntryReward: 2,
    difficulty: 'hard',
    category: 'photo_video',
    startingPath: 'challenge',
    verificationType: 'video',
    proofRequirement: 'Upload a short video or proof link from the approved partner area.',
    isFlash: false,
    status: 'inactive',
    sortOrder: 5,
    createdAt: '2026-08-01T00:00:00Z',
    safetyNotes: 'Partner permission required. Family-friendly hours only; no alcohol purchase or adult-only access may be required.',
    gmNotes: 'Partner-ready slot. Confirm venue name, hours, minor policy, and exact proof backdrop before activation.',
  },
  {
    id: 'qst-palace-theatre-year',
    eventId: SEED_EVENT.id,
    locationId: 'loc-music-hall',
    location: SEED_LOCATIONS[5],
    title: 'The Palace Lantern Date',
    slug: 'palace-theatre-lore',
    description: 'The Palace Theatre has been showing its founding date to Canton for over a century. Most people walk past it without reading.',
    instructions: 'Stand on the public sidewalk in front of Canton Palace Theatre on Market Ave N. Find the four-digit year displayed on the exterior of the building itself — not a sign or poster, but part of the structure. Enter it below. No ticket purchase required.',
    pointValue: 125,
    xpReward: 125,
    drawingEntryReward: 1,
    difficulty: 'easy',
    category: 'trivia',
    startingPath: 'family',
    verificationType: 'passphrase',
    proofRequirement: 'Enter the four-digit year from the approved exterior marker.',
    isFlash: false,
    status: 'active',
    sortOrder: 6,
    createdAt: '2026-08-01T00:00:00Z',
    safetyNotes: 'Stay on public sidewalks and keep theatre entrances clear. No ticket purchase is required.',
    gmNotes: 'Existing server hash expects the verified four-digit answer. Reconfirm marker text before launch.',
  },
  {
    id: 'qst-market-square-flash',
    eventId: SEED_EVENT.id,
    locationId: 'loc-centennial-plaza',
    location: SEED_LOCATIONS[0],
    title: 'Flash Drop — Market Square Signal',
    slug: 'market-square-flash',
    description: 'The Game Master just opened a 45-minute window. Drop everything and move.',
    instructions: 'Get to Centennial Plaza and check in before the window closes. This signal is live right now. Tap CHECK IN from the plaza — the window expires at the time displayed. GPS must confirm your position. No clue needed. Just be there.',
    pointValue: 225,
    xpReward: 225,
    drawingEntryReward: 2,
    difficulty: 'medium',
    category: 'flash',
    startingPath: 'cross_city',
    verificationType: 'checkin',
    proofRequirement: 'Timed GPS check-in during an active Game Master flash window.',
    isFlash: true,
    startsAt: '2026-09-12T19:00:00Z',
    expiresAt: '2026-09-12T19:45:00Z',
    status: 'active',
    sortOrder: 7,
    createdAt: '2026-08-01T00:00:00Z',
    radiusMeters: 60,
    requireLocationVerification: true,
    safetyNotes: 'No running into traffic or cutting through restricted areas. The drop is optional and should be paused if the plaza is crowded or closed.',
    gmNotes: 'Use live controls to adjust the active window based on weather and field conditions.',
  },
  {
    id: 'qst-onesto-brass-motto',
    eventId: SEED_EVENT.id,
    locationId: 'loc-onesto-building',
    location: SEED_LOCATIONS[7],
    title: 'The Brass Door Key',
    slug: 'onesto-brass-motto',
    description: 'A downtown doorway has been holding a one-word message in its architectural detail since the building opened.',
    instructions: 'Go to the Onesto building at 225 2nd St NW. From the public sidewalk, inspect the brass architectural detail near the main entrance. Find the single word inscribed in the metalwork — it is not a name, but a word that describes what a building or institution aspires to be. Enter it below. Capitalization does not matter.',
    pointValue: 150,
    xpReward: 150,
    drawingEntryReward: 1,
    difficulty: 'medium',
    category: 'observation',
    startingPath: 'challenge',
    verificationType: 'passphrase',
    proofRequirement: 'Enter the exact word from the approved public-facing architectural detail.',
    isFlash: false,
    status: 'active',
    sortOrder: 8,
    createdAt: '2026-08-01T00:00:00Z',
    safetyNotes: 'Public sidewalk view only. Do not enter private residential or lobby areas unless invited by posted public access.',
    gmNotes: 'Reconfirm visible clue target and public viewing boundary before launch.',
  },
  {
    id: 'qst-hof-legend-qr',
    eventId: SEED_EVENT.id,
    locationId: 'loc-hof-trail',
    location: SEED_LOCATIONS[6],
    title: 'The Helmet Trail Emblem',
    slug: 'hof-trail-emblem',
    description: 'The Hall of Fame trail has a hidden emblem. High-value. High distance. All worth it.',
    instructions: 'Follow the Hall of Fame trail to the approved public marker location near 2121 George Halas Dr NW. Find the official Canton Quests QR emblem mounted at the approved fixture — it is weatherproofed and visible at eye level. Look for the Canton Quests seal. You have to travel to earn it. Enter the QR passcode below.',
    pointValue: 325,
    xpReward: 325,
    drawingEntryReward: 2,
    difficulty: 'hard',
    category: 'trivia',
    startingPath: 'challenge',
    verificationType: 'qr',
    proofRequirement: 'Enter the QR passcode from the official field emblem.',
    isFlash: false,
    status: 'active',
    sortOrder: 9,
    createdAt: '2026-08-01T00:00:00Z',
    requireQrAndLocation: true,
    radiusMeters: 75,
    safetyNotes: 'Use marked pedestrian routes and daylight hours. Do not cross traffic outside crosswalks.',
    gmNotes: 'Human verification required for exact placement, permission, QR weatherproofing, and pedestrian safety.',
  },
  {
    id: 'qst-frankenstein-west-lawn',
    eventId: SEED_EVENT.id,
    locationId: 'loc-west-lawn-frankenstein',
    location: SEED_LOCATIONS[8],
    title: 'The Watchers of West Lawn',
    slug: 'watchers-west-lawn',
    description: 'Three monuments. Three observations. One passphrase. A century of Canton history encoded in stone.',
    instructions:
      'Visit West Lawn Cemetery during public daylight hours. Locate three specific monuments — the Family Stone, the Year of Stone, and the Soldier — and record one detail from each. Combine them into the final passphrase. Stay on paved or gravel paths at all times. Do not touch, lean on, or sit on any monument. Leave everything exactly as you found it.',
    pointValue: 300,
    xpReward: 300,
    drawingEntryReward: 2,
    difficulty: 'hard',
    category: 'secret',
    startingPath: 'secret',
    verificationType: 'multi_step',
    proofRequirement:
      'Verify all three monument observations in sequence. Final combined passphrase unlocks the full reward. Upload a respectful daytime photo with your callsign card and at least one monument visible from a public path.',
    isFlash: false,
    status: 'active',
    sortOrder: 10,
    createdAt: '2026-08-01T00:00:00Z',
    isSecret: true,
    steps: [
      {
        id: 'step-watcher-1-family-stone',
        questId: 'qst-frankenstein-west-lawn',
        stepOrder: 1,
        title: 'Watcher 1 — The Family Stone',
        instructions:
          'Find the large family monument whose surname became famous in fiction long after this Canton family used it. The name is carved at the base. Enter the full surname exactly as it appears on the stone.',
        verificationType: 'passphrase',
      },
      {
        id: 'step-watcher-2-year-of-stone',
        questId: 'qst-frankenstein-west-lawn',
        stepOrder: 2,
        title: 'Watcher 2 — The Year of Stone',
        instructions:
          'Find a monument in the older section of the cemetery bearing a four-digit year carved into the structure itself — not on a name plate. The number marks a founding, construction, or dedication. Enter the four-digit year.',
        verificationType: 'passphrase',
      },
      {
        id: 'step-watcher-3-the-soldier',
        questId: 'qst-frankenstein-west-lawn',
        stepOrder: 3,
        title: 'Watcher 3 — The Soldier',
        instructions:
          'Find a standing soldier monument from the Civil War era. What does the soldier hold? Enter that single word. Then combine all three: last four letters of Watcher 1\'s name + final two digits of Watcher 2\'s year + Watcher 3\'s object, as one word with no spaces, to unlock the final reward.',
        verificationType: 'passphrase',
      },
    ],
    safetyNotes:
      'Daylight only. Confirm cemetery hours before visiting. Stay on paved or gravel paths. No touching, climbing, rubbing, decorating, moving items, loud behavior, nighttime access, or interference with graves, markers, visitors, or staff.',
    gmNotes:
      'MUST complete site walk before launch: (1) confirm Frankenstein monument exact spelling, (2) identify Year of Stone monument and confirm year, (3) identify Soldier monument and confirm what it holds, (4) set server hashes for all three steps and the final combined passphrase, (5) confirm cemetery daytime hours and any photography rules.',
  },
  {
    id: 'qst-secret-cipher-77',
    eventId: SEED_EVENT.id,
    locationId: 'loc-4th-st-mural',
    location: SEED_LOCATIONS[2],
    title: "The Founder's Three Locks",
    slug: 'secret-cipher-77',
    description: 'Three downtown fragments. Three locks. This chain only opens for agents who have already done the work.',
    instructions:
      'Collect three cipher fragments from your completed downtown missions — one from the Founder route, one from the Painted Witness, one from the Brass Door Key. Each fragment was embedded in a physical clue card at its location. Enter them in sequence. Each lock only appears after the previous one verifies.',
    pointValue: 650,
    xpReward: 650,
    drawingEntryReward: 4,
    difficulty: 'epic',
    category: 'secret',
    startingPath: 'secret',
    verificationType: 'multi_step',
    proofRequirement: 'Verify all three field-fragment passphrases in sequence.',
    isFlash: false,
    status: 'active',
    sortOrder: 11,
    createdAt: '2026-08-01T00:00:00Z',
    isSecret: true,
    prerequisiteQuestId: 'qst-onesto-brass-motto',
    unlockConditionType: 'prerequisite',
    steps: [
      {
        id: 'step-secret-founder-fragment',
        questId: 'qst-secret-cipher-77',
        stepOrder: 1,
        title: 'Lock One: Founder Fragment',
        instructions: 'Use the fragment revealed by the Founder Signal route. Enter only the field phrase printed on the approved physical clue.',
        verificationType: 'passphrase',
      },
      {
        id: 'step-secret-mural-fragment',
        questId: 'qst-secret-cipher-77',
        stepOrder: 2,
        title: 'Lock Two: Painted Fragment',
        instructions: 'Use the fragment connected to the Painted Witness. Enter the field phrase exactly as it appears in the event clue.',
        verificationType: 'passphrase',
      },
      {
        id: 'step-secret-brass-fragment',
        questId: 'qst-secret-cipher-77',
        stepOrder: 3,
        title: 'Lock Three: Brass Fragment',
        instructions: 'Use the final fragment from the Brass Door Key. Enter the field phrase to close the chain and claim the mystery reward.',
        verificationType: 'passphrase',
      },
    ],
    safetyNotes: 'Use only public sidewalks and approved partner/public spaces while gathering fragments.',
    gmNotes: 'Do not publish fragment answers. Confirm all three fragment cards are placed, ordered, and mapped to server step hashes before enabling this chain for competitive play.',
  },
  {
    id: 'qst-founders-secret-clue',
    eventId: SEED_EVENT.id,
    locationId: 'loc-centennial-plaza',
    location: SEED_LOCATIONS[0],
    title: "The Founder's Keystone",
    slug: 'founders-secret-clue',
    description: 'The opening signal reveals a second mark at the plaza.',
    instructions:
      'After opening the Founder Signal, inspect the approved public clue card or marker at Centennial Plaza and enter the keystone word.',
    // STATUS: Inactive at launch — cuts roster redundancy at Centennial Plaza
    pointValue: 150,
    xpReward: 150,
    drawingEntryReward: 1,
    difficulty: 'medium',
    category: 'puzzle',
    startingPath: 'family',
    verificationType: 'passphrase',
    proofRequirement: 'Enter the keystone word from the approved physical clue.',
    isFlash: false,
    status: 'inactive',  // Cut from Sept 11 launch — redundant Centennial Plaza quest
    sortOrder: 12,
    createdAt: '2026-08-01T00:00:00Z',
    radiusMeters: 60,
    prerequisiteQuestId: 'qst-centennial-discovery',
    unlockConditionType: 'prerequisite',
    requireLocationVerification: true,
    safetyNotes: 'Stay in public plaza areas and do not move or alter any clue card or fixture.',
    gmNotes: 'Server hash expects launch clue value. Place clue card only after final field route check.',
  },
  {
    id: 'qst-palace-flash-popup',
    eventId: SEED_EVENT.id,
    locationId: 'loc-music-hall',
    location: SEED_LOCATIONS[5],
    title: 'Flash Drop — Palace Lantern Cipher',
    slug: 'palace-marquee-flash',
    description: '30 minutes. A live cipher at the Palace. This one disappears at midnight.',
    instructions:
      'Get to Canton Palace Theatre on Market Ave N. The Game Master has activated a temporary passcode display near the Palace exterior — visible from the public sidewalk. Find it and enter the active flash passcode before the timer expires. Well-lit. Public. Fast.',
    pointValue: 275,
    xpReward: 275,
    drawingEntryReward: 2,
    difficulty: 'hard',
    category: 'flash',
    startingPath: 'cross_city',
    verificationType: 'passphrase',
    proofRequirement: 'Enter flash passcode before expiry.',
    isFlash: true,
    startsAt: '2026-09-12T23:00:00Z',
    expiresAt: '2026-09-12T23:30:00Z',
    status: 'active',
    sortOrder: 13,
    createdAt: '2026-08-01T00:00:00Z',
    safetyNotes:
      'Only activate if the sidewalk is well lit, public, and calm. No road crossings outside marked crosswalks and no building entry required.',
    gmNotes: 'Evening flash is optional. Cancel if weather, crowding, or lighting creates field risk.',
  },
  {
    id: 'qst-civic-seal-photo',
    eventId: SEED_EVENT.id,
    locationId: 'loc-centennial-plaza',
    location: SEED_LOCATIONS[0],
    title: 'The Civic Seal Snapshot',
    slug: 'civic-seal-snapshot',
    description: 'A family-friendly photo stop that turns the city center into a team badge moment.',
    instructions:
      'Find an approved public civic backdrop near the plaza and take a photo of your team/callsign card making a clear Canton Quests victory mark.',
    pointValue: 125,
    xpReward: 125,
    drawingEntryReward: 1,
    difficulty: 'easy',
    category: 'creative',
    startingPath: 'family',
    verificationType: 'photo',
    proofRequirement: 'Upload a photo or proof link from the approved public civic backdrop.',
    isFlash: false,
    status: 'inactive',  // Cut from Sept 11 launch — generic plaza photo, no distinct media
    sortOrder: 14,
    createdAt: '2026-08-01T00:00:00Z',
    safetyNotes: 'Keep sidewalks clear and do not photograph strangers closely without consent.',
    gmNotes: 'Pick final backdrop after human site walk; avoid exposing private business entrances or minors in public recap feeds.',
  },
  // Challenge Path — Mother Goose Land
  {
    id: 'qst-goose-land-cipher',
    eventId: SEED_EVENT.id,
    locationId: 'loc-mother-goose-land',
    location: undefined,
    title: 'The Goose Land Cipher',
    slug: 'goose-land-cipher',
    description: "Canton's most nostalgic landmark is hiding a word in the mural wall. It has always been there.",
    instructions:
      'Go to Mother Goose Land at 714 12th St NW. Find the large illustrated mural wall. The answer is embedded in the mural — not written as a label, but depicted as an image. What is the character in the lower right section of the wall holding? Enter that single word. Lowercase, no spaces.',
    pointValue: 175,
    xpReward: 175,
    drawingEntryReward: 1,
    difficulty: 'medium',
    category: 'observation',
    startingPath: 'challenge',
    verificationType: 'passphrase',
    proofRequirement: 'Enter the single word for the depicted object in the mural.',
    isFlash: false,
    status: 'active',
    sortOrder: 16,
    createdAt: '2026-08-01T00:00:00Z',
    radiusMeters: 60,
    safetyNotes: 'Open public park. Daylight hours only. Respect any seasonal closures or maintenance areas.',
    gmNotes: 'MUST confirm on site before launch: (1) visit the mural wall and verify exact detail + single-word answer, (2) set server passphrase hash, (3) confirm park is accessible on event weekend, (4) confirm seasonal operating status.',
  },
  // Finale Quest
  {
    id: 'qst-grand-finale-cipher',
    eventId: SEED_EVENT.id,
    locationId: 'loc-centennial-plaza',
    location: SEED_LOCATIONS[0],
    title: "Finale — The Founder's Master Key",
    slug: 'grand-finale-cipher',
    description: 'One key. One lock. The entire weekend has been leading here.',
    instructions: 'Qualified agents receive a final prompt from the Game Master during Finale Mode. Watch the official broadcast channel — the Master Key will be issued there. Enter it exactly as issued. No guessing. This key is unique to the finale event and expires when the window closes.',
    pointValue: 900,
    xpReward: 900,
    drawingEntryReward: 5,
    difficulty: 'epic',
    category: 'finale',
    startingPath: 'cross_city',
    verificationType: 'passphrase',
    proofRequirement: 'Finale qualification and official Game Master prompt required.',
    isFlash: false,
    isFinaleQuest: true,
    status: 'active',
    sortOrder: 15,
    createdAt: '2026-08-01T00:00:00Z',
    unlockConditionType: 'manual',
    safetyNotes: 'Finale prompt must never require rushing, trespassing, unsafe driving, or nighttime cemetery access.',
    gmNotes: 'Keep inactive until finale operations are staffed. Confirm drawing ledger status before awarding final entries.',
  },
];
