-- THE GRID — Comms 5: incremental message sync and channel notification preferences.

alter table public.grid_chat_messages
  add column sequence_no bigint generated by default as identity;

create unique index grid_chat_messages_sequence_uq
  on public.grid_chat_messages (sequence_no);
create index grid_chat_messages_channel_sequence_idx
  on public.grid_chat_messages (channel_id, sequence_no desc);

create or replace function public.grid_chat_unread_count(
  p_channel_id uuid,
  p_player_id uuid
)
returns bigint
language plpgsql
security invoker
stable
set search_path = ''
as $$
declare
  v_last_read_at timestamptz;
  v_count bigint;
begin
  select m.last_read_at
    into v_last_read_at
    from public.grid_chat_members m
   where m.channel_id = p_channel_id
     and m.player_id = p_player_id
     and m.left_at is null;
  if not found then raise exception 'CHAT_MEMBERSHIP_REQUIRED'; end if;

  select count(*)
    into v_count
    from public.grid_chat_messages m
   where m.channel_id = p_channel_id
     and m.status = 'visible'
     and (v_last_read_at is null or m.created_at > v_last_read_at)
     and (
       m.sender_kind = 'system'
       or (
         m.sender_player_id is not null
         and m.sender_player_id <> p_player_id
         and not exists (
           select 1
             from public.grid_chat_blocks b
            where b.blocker_player_id = p_player_id
              and b.blocked_player_id = m.sender_player_id
         )
       )
     );

  return v_count;
end;
$$;

create or replace function public.grid_set_chat_notifications(
  p_channel_id uuid,
  p_player_id uuid,
  p_enabled boolean
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
begin
  update public.grid_chat_members
     set notifications_enabled = p_enabled
   where channel_id = p_channel_id
     and player_id = p_player_id
     and left_at is null;
  if not found then raise exception 'CHAT_MEMBERSHIP_REQUIRED'; end if;

  return jsonb_build_object(
    'channelId', p_channel_id,
    'notificationsEnabled', p_enabled
  );
end;
$$;

revoke all on function public.grid_chat_unread_count(uuid, uuid) from public, anon, authenticated;
grant execute on function public.grid_chat_unread_count(uuid, uuid) to service_role;
revoke all on function public.grid_set_chat_notifications(uuid, uuid, boolean) from public, anon, authenticated;
grant execute on function public.grid_set_chat_notifications(uuid, uuid, boolean) to service_role;
